# Generated by Django 4.2.6 on 2023-10-07 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("offices", "0001_initial"),
        ("roles", "0001_initial"),
        ("authentication", "0002_alter_user_birthday"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="office",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="offices.office",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, to="roles.role"
            ),
            preserve_default=False,
        ),
    ]
