# Generated by Django 4.2.6 on 2023-10-07 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("offices", "0001_initial"),
        ("authentication", "0003_user_office_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="office",
            field=models.ForeignKey(
                default=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="offices.office",
            ),
        ),
    ]
