# Generated by Django 4.2.6 on 2023-10-07 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("roles", "0001_initial"),
        ("authentication", "0004_alter_user_office"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.ForeignKey(
                default=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="roles.role",
            ),
        ),
    ]
