# Generated by Django 4.2.6 on 2023-10-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0007_user_is_banned"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_banned",
            field=models.BooleanField(default=False, verbose_name="Клиент"),
        ),
    ]
