# Generated by Django 4.2.5 on 2023-12-02 01:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0007_user_login_logout_times"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_new",
            field=models.BooleanField(
                default=True,
                help_text="Определяет, новый ли пользователь",
                verbose_name="Новый пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.CharField(
                blank=True, default=False, max_length=10, verbose_name="Активность"
            ),
        ),
    ]
