# Generated by Django 4.2.6 on 2023-11-10 16:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0009_alter_user_is_banned"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="office",
            new_name="OfficeID",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="role",
            new_name="RoleID",
        ),
    ]
