# Generated by Django 4.2.1 on 2023-11-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0015_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(default="your_default_value", max_length=255),
        ),
    ]
