# Generated by Django 4.2.6 on 2023-10-10 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aircraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("make_model", models.CharField(max_length=255)),
                ("total_seats", models.PositiveIntegerField()),
                ("economy_seats", models.PositiveIntegerField()),
                ("business_seats", models.PositiveIntegerField()),
            ],
        ),
    ]
