# Generated by Django 4.2.1 on 2023-11-11 17:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("aircrafts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="aircraft",
            old_name="business_seats",
            new_name="BusinessSeats",
        ),
        migrations.RenameField(
            model_name="aircraft",
            old_name="economy_seats",
            new_name="EconomySeats",
        ),
        migrations.RenameField(
            model_name="aircraft",
            old_name="make_model",
            new_name="MakeModel",
        ),
        migrations.RenameField(
            model_name="aircraft",
            old_name="name",
            new_name="Name",
        ),
        migrations.RenameField(
            model_name="aircraft",
            old_name="total_seats",
            new_name="TotalSeats",
        ),
    ]
