# Generated by Django 4.2.6 on 2023-11-10 16:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("offices", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="office",
            old_name="country",
            new_name="CountryID",
        ),
    ]
