# Generated by Django 4.2.1 on 2023-11-11 17:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("offices", "0002_rename_country_office_countryid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="office",
            old_name="contact",
            new_name="Contact",
        ),
        migrations.RenameField(
            model_name="office",
            old_name="phone",
            new_name="Phone",
        ),
        migrations.RenameField(
            model_name="office",
            old_name="title",
            new_name="Title",
        ),
    ]
