# Generated by Django 4.2.1 on 2023-11-11 17:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("amenities", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="amenity",
            old_name="price",
            new_name="Price",
        ),
        migrations.RenameField(
            model_name="amenity",
            old_name="service",
            new_name="Service",
        ),
    ]
