# Generated by Django 4.2.5 on 2023-11-24 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0001_initial"),
        ("cabintypes", "0001_initial"),
        ("amenities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AmenityTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=19),
                ),
                (
                    "amenity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="amenities.amenity",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tickets.ticket"
                    ),
                ),
            ],
            options={
                "unique_together": {("amenity", "ticket")},
            },
        ),
        migrations.CreateModel(
            name="AmenityCabinType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amenity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="amenities.amenity",
                    ),
                ),
                (
                    "cabin_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cabintypes.cabintype",
                    ),
                ),
            ],
            options={
                "unique_together": {("cabin_type", "amenity")},
            },
        ),
    ]
