# Generated by Django 4.2.1 on 2023-11-11 17:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("airports", "0002_rename_country_airport_countryid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="airport",
            old_name="name",
            new_name="Name",
        ),
    ]
