# Generated by Django 4.2.6 on 2023-10-10 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("сabintyps", "0001_initial"),
        ("countries", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("schedules", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255)),
                ("phone", models.CharField(max_length=20)),
                ("passport_number", models.CharField(max_length=255)),
                ("booking_reference", models.CharField(max_length=255)),
                ("confirmed", models.BooleanField(default=False)),
                (
                    "cabin_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="сabintyps.cabintype",
                    ),
                ),
                (
                    "passport_country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="countries.country",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schedules.schedule",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
