# Generated by Django 4.2.6 on 2023-11-10 16:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ticket",
            old_name="cabin_type",
            new_name="CabinTypeID",
        ),
        migrations.RenameField(
            model_name="ticket",
            old_name="passport_country",
            new_name="PassportCountryID",
        ),
        migrations.RenameField(
            model_name="ticket",
            old_name="schedule",
            new_name="ScheduleID",
        ),
        migrations.RenameField(
            model_name="ticket",
            old_name="user",
            new_name="UserID",
        ),
    ]
