# Generated by Django 4.2.1 on 2023-11-11 17:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0002_rename_cabin_type_ticket_cabintypeid_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ticket",
            old_name="booking_reference",
            new_name="bookingreference",
        ),
        migrations.RenameField(
            model_name="ticket",
            old_name="first_name",
            new_name="firstname",
        ),
        migrations.RenameField(
            model_name="ticket",
            old_name="last_name",
            new_name="lastname",
        ),
        migrations.RenameField(
            model_name="ticket",
            old_name="passport_number",
            new_name="passportnumber",
        ),
    ]
