@BACKEND_URL = http://localhost:8000/api


### Login
# @name login 
POST {{BACKEND_URL}}/auth/login/
Content-Type: application/json

{
    "email": "wtf403@yandex.ru",
    "password": "admin"
}

### Me
# @ name me
# @ref login
GET {{BACKEND_URL}}/auth/me/
Content-Type: application/json
Authorization: Bearer {{login.access}}

### Logout
# @ref login
POST {{BACKEND_URL}}/auth/logout/
Content-Type: application/json
Authorization: Bearer {{login.access}}

{
    "id": 1,
    "email": "wtf403@ya.ru",
    "password": "admin"
}
{{
    console.log(response.parsedBody)
}}
