# @import auth.http

### Get schedules
# @ref login 
GET {{BACKEND_URL}}/schedules/
Content-Type: application/json

### Update flight
# @ref login 
PATCH {{BACKEND_URL}}/schedules/1/
Content-Type: application/json
Authorization: Bearer {{login.access}}
{
    "date": "2023-01-01",
    "time": "12:00:00",
    "price": 2000.00
}


### Cancel flight
# @ref login 
POST {{BACKEND_URL}}/schedules/cancel/2/
Content-Type: application/json
Authorization: Bearer {{login.access}}



### Import schedules
# @ref login 
POST {{BACKEND_URL}}/schedules/import-csv/
Authorization: Bearer {{login.access}}
Content-Type: multipart/form-data; boundary=WebKitFormBoundary

invoice_title
--WebKitFormBoundary
Content-Disposition: form-data; name="file"; filename="Schedules_V12_2.csv"
Content-Type: text/csv

< ./Schedules_V12_2.csv
--WebKitFormBoundary--


