# @import auth.http

### Get all tickets
# @ref login 
GET {{BACKEND_URL}}/tickets/
Content-Type: application/json

### Search ticket
POST {{BACKEND_URL}}/tickets/search/
Content-Type: application/json

{
  "from_airport": "BAH",
  "to_airport": "AUH",
  "cabin_type": "economy",
  "outbound_date": "2017-10-07",
  "return_date": "2017-10-09",
  "wide_search": true 
}

/*
{
  "outbound": [
    {
      "id": 8,
      "from": "BAH",
      "to": "AUH",
      "date": "2017-10-07",
      "time": "21:09:00",
      "flight_numbers": [
        50
      ],
      "base_price": 405
    }
  ],
  "return": [
    {
      "id": 11,
      "from": "AUH",
      "to": "BAH",
      "date": "2017-10-09",
      "time": "17:00:00",
      "flight_numbers": [
        49
      ],
      "base_price": 627
    }
  ]
}
*/


### Issue ticket 
POST {{BACKEND_URL}}/tickets/issue-ticket/
Content-Type: application/json

{
    "user": 1,
    "schedule": 1,
    "cabin_type": "First class",
    "first_name": "John",
    "last_name": "Smith",
    "email": "test@test.com",
    "phone": "123456789",
    "passport_number": "123456789",
    "passport_country_id": 145,
    "booking_reference": "123456",
    "confirmed": true
}
