# @import auth.http

### Get all tickets
# @ref login 
GET {{BACKEND_URL}}/tickets/
Content-Type: application/json

### Search ticket (session 3)
POST {{BACKEND_URL}}/tickets/search/
{
  "from_airport": "BAH",
  "to_airport": "AUH",
  "cabin_type": "economy",
  "outbound_date": "2017-10-04"
}


