# Generated by Django 4.2.5 on 2023-12-02 01:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedules", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="FlightNumber",
            field=models.IntegerField(default=False),
            preserve_default=False,
        ),
    ]
