# Generated by Django 4.2.6 on 2023-11-10 16:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("schedules", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="schedule",
            old_name="aircraft",
            new_name="AircraftID",
        ),
        migrations.RenameField(
            model_name="schedule",
            old_name="route",
            new_name="RouteID",
        ),
    ]
