# Generated by Django 4.2.1 on 2023-11-11 17:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("schedules", "0002_rename_aircraft_schedule_aircraftid_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="schedule",
            old_name="economy_price",
            new_name="economyprice",
        ),
        migrations.RenameField(
            model_name="schedule",
            old_name="flight_number",
            new_name="flightnumber",
        ),
    ]
