# Generated by Django 4.2.1 on 2023-11-11 17:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("schedules", "0003_rename_economy_price_schedule_economyprice_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="schedule",
            old_name="confirmed",
            new_name="Confirmed",
        ),
        migrations.RenameField(
            model_name="schedule",
            old_name="date",
            new_name="Date",
        ),
        migrations.RenameField(
            model_name="schedule",
            old_name="economyprice",
            new_name="EconomyPrice",
        ),
        migrations.RenameField(
            model_name="schedule",
            old_name="flightnumber",
            new_name="FlightNumber",
        ),
        migrations.RenameField(
            model_name="schedule",
            old_name="time",
            new_name="Time",
        ),
    ]
