# Generated by Django 4.2.6 on 2023-11-10 16:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("routes", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="route",
            old_name="arrival_airport",
            new_name="ArrivalAirportID",
        ),
        migrations.RenameField(
            model_name="route",
            old_name="departure_airport",
            new_name="DepartureAirportID",
        ),
    ]
