# Generated by Django 4.2.1 on 2023-11-11 17:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("routes", "0002_rename_arrival_airport_route_arrivalairportid_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="route",
            old_name="flight_time",
            new_name="flighttime",
        ),
    ]
