# Generated by Django 4.2.1 on 2023-11-11 17:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("routes", "0003_rename_flight_time_route_flighttime"),
    ]

    operations = [
        migrations.RenameField(
            model_name="route",
            old_name="distance",
            new_name="Distance",
        ),
        migrations.RenameField(
            model_name="route",
            old_name="flighttime",
            new_name="FlightTime",
        ),
    ]
