# Generated by Django 4.2.1 on 2023-11-11 17:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("countries", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="country",
            old_name="name",
            new_name="Name",
        ),
    ]
