# Generated by Django 4.2.6 on 2023-10-11 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("сabintyps", "0001_initial"),
        ("amenities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AmenityCabinType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amenity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="amenities.amenity",
                    ),
                ),
                (
                    "cabin_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="сabintyps.cabintype",
                    ),
                ),
            ],
        ),
    ]
