# Generated by Django 4.2.6 on 2023-11-10 16:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("amenity_cabin_types", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="amenitycabintype",
            old_name="amenity",
            new_name="AmenityID",
        ),
        migrations.RenameField(
            model_name="amenitycabintype",
            old_name="cabin_type",
            new_name="Cabin_typeID",
        ),
    ]
