# Generated by Django 4.2.6 on 2023-11-10 16:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "amenity_cabin_types",
            "0002_rename_amenity_amenitycabintype_amenityid_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="amenitycabintype",
            old_name="Cabin_typeID",
            new_name="CabinTypeID",
        ),
    ]
