# Generated by Django 4.2.6 on 2023-11-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amenity_tickets", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="amenityticket",
            old_name="amenity",
            new_name="AmenityID",
        ),
        migrations.RenameField(
            model_name="amenityticket",
            old_name="ticket",
            new_name="TicketID",
        ),
        migrations.AddField(
            model_name="amenityticket",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
