# Generated by Django 4.2.1 on 2023-11-11 17:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("amenity_tickets", "0002_rename_amenity_amenityticket_amenityid_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="amenityticket",
            old_name="price",
            new_name="Price",
        ),
    ]
